const tiendaconfig = {
  productsconfig: {
    headers: [
      "Handle",
      "Title",
      "Body (HTML)",
      "Vendor",
      "Type",
      "Tags",
      "Published",
      "Option1 Name",
      "Option1 Value",
      "Option2 Name",
      "Option2 Value",
      "Option3 Name",
      "Option3 Value",
      "Variant SKU",
      "Variant Grams",
      "Variant Inventory Tracker",
      "Variant Inventory Qty",
      "Variant Inventory Policy",
      "Variant Fulfillment Service",
      "Variant Price",
      "Variant Compare At Price",
      "Variant Requires Shipping",
      "Variant Taxable",
      "Variant Barcode",
      "Image Src",
      "Image Position",
      "Image Alt Text",
      "Gift Card",
      "SEO Title",
      "SEO Description",
      "Google Shopping / Google Product Category",
      "Google Shopping / Gender",
      "Google Shopping / Age Group",
      "Google Shopping / MPN",
      "Google Shopping / AdWords Grouping",
      "Google Shopping / AdWords Labels",
      "Google Shopping / Condition",
      "Google Shopping / Custom Product",
      "Google Shopping / Custom Label 0",
      "Google Shopping / Custom Label 1",
      "Google Shopping / Custom Label 2",
      "Google Shopping / Custom Label 3",
      "Google Shopping / Custom Label 4",
      "Variant Image",
      "Variant Weight Unit",
      "Variant Tax Code",
      "Cost per item",
      "Collection",
    ],
    polera_H: {
      name: "Poleras hombre",
      precio: 12990,
      costo: 4400,
      peso: "200.0",
      colorfavs: ["blanco", "negro", "gris"]
    },
    polera_M: {
      name: "Poleras mujer",
      precio: 12990,
      costo: 4400,
      peso: "200.0",
    },
    polerones: {
      name: "Polerones",
      precio: 19990,
      costo: 11300,
      colores: ["gris", "negro", "azul", "rojo"],
      peso: "300.0",
      colorfavs:["gris", "negro", "azul", "rojo"]
    },
    tallas: ["S", "M", "L", "XL"],
    colores: {
      blanco: "blanco",
      negro: "negro",
      gris: "gris",
      gris_osc: "gris oscuro",
      azul: "azul",
      azul_mar: "azul marino",
      azul_opa: "azul opaco",
      verde_agu: "verde agua",
      verde_osc: "verde oscuro",
      rojo: "rojo",
      vinotinto: "vinotinto",
      array: [
        "blanco",
        "negro",
        "gris",
        "gris oscuro",
        "azul",
        "azul marino",
        "azul opaco",
        "verde agua",
        "verde oscuro",
        "rojo",
        "vinotinto",
      ],
      array_poleron : [
        "negro",
        "gris",
        "azul",
        "rojo",
      ]
    },
  },
};

module.exports = tiendaconfig;